# Generated by Django 4.2 on 2025-07-18 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('design_id', models.UUIDField()),
                ('customer_details', models.JSONField()),
                ('order_options', models.JSONField()),
                ('standard_sizes', models.JSONField()),
                ('custom_sizes', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
