# Generated by Django 4.2 on 2025-07-21 15:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customize_clothes', '0007_design_svg_data'),
        ('submit_order', '0002_remove_order_customer_details_remove_order_design_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('chest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('waist', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hip', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shoulder', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sleeve', models.DecimalField(decimal_places=2, max_digits=5)),
                ('shirt_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('neck', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='StandardSizeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=3)),
                ('quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='custom_sizes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='nametags',
        ),
        migrations.RemoveField(
            model_name='order',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='standard_sizes',
        ),
        migrations.RemoveField(
            model_name='order',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='has_custom_sizes',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='other_role',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='role',
            field=models.CharField(choices=[('hr', 'HR Manager'), ('admin', 'Administrator'), ('purchasing', 'Purchasing Department'), ('manager', 'Department Manager'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customize_clothes.design'),
        ),
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
        migrations.AddField(
            model_name='standardsizequantity',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standard_sizes', to='submit_order.order'),
        ),
        migrations.AddField(
            model_name='customsize',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_sizes', to='submit_order.order'),
        ),
        migrations.AlterUniqueTogether(
            name='standardsizequantity',
            unique_together={('order', 'gender', 'size')},
        ),
    ]
