# Generated by Django 4.2 on 2025-07-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_order', '0004_order_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
