# Generated by Django 4.2 on 2025-07-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submit_order', '0005_order_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='order submitted', max_length=20),
        ),
    ]
