# Generated by Django 4.2 on 2025-07-22 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submitquotation', '0003_remove_quotation_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_proof', models.FileField(upload_to='payment_proofs/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('admin_action_date', models.DateTimeField(blank=True, null=True)),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='submitquotation.quotation')),
            ],
        ),
    ]
