# Generated by Django 4.2 on 2025-07-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('payment_proof', models.FileField(upload_to='payment_proofs/')),
                ('notes', models.TextField(blank=True, null=True)),
                ('payment_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_remark', models.TextField(blank=True, null=True)),
                ('admin_action_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
