# Generated by Django 4.2 on 2025-07-17 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managesizechart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sizechart',
            options={'ordering': ['-is_active', 'gender', 'size_type', 'name']},
        ),
        migrations.AddField(
            model_name='sizechart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
