# Generated by Django 4.2 on 2025-07-26 11:25

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmedPayment',
            fields=[
            ],
            options={
                'verbose_name': 'Confirmed Payment',
                'verbose_name_plural': 'Confirmed Payments',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('payment.payment',),
        ),
    ]
