# Generated by Django 4.2 on 2025-07-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('design_data', models.JSONField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='design_images/')),
                ('svg_data', models.TextField(blank=True, null=True)),
                ('svg_file', models.FileField(blank=True, null=True, upload_to='design_svgs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
