# Generated by Django 4.2 on 2025-07-18 18:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShirtDesign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('design_svg', models.FileField(upload_to='shirt_designs/')),
                ('colors', models.JSONField()),
                ('design_elements', models.JSONField()),
                ('pockets', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
