# Generated by Django 4.2 on 2025-07-20 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize_clothes', '0002_design_delete_shirtdesign'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='svg_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
