# Generated by Django 4.2 on 2025-07-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize_clothes', '0003_design_svg_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='svg_file',
            field=models.FileField(blank=True, null=True, upload_to='design_svgs/'),
        ),
    ]
