# Generated by Django 4.2 on 2025-07-21 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize_clothes', '0004_design_svg_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='svg_data',
        ),
        migrations.RemoveField(
            model_name='design',
            name='svg_file',
        ),
        migrations.AddField(
            model_name='design',
            name='svg_back',
            field=models.FileField(blank=True, null=True, upload_to='design_svgs/'),
        ),
        migrations.AddField(
            model_name='design',
            name='svg_front',
            field=models.FileField(blank=True, null=True, upload_to='design_svgs/'),
        ),
        migrations.AddField(
            model_name='design',
            name='svg_left',
            field=models.FileField(blank=True, null=True, upload_to='design_svgs/'),
        ),
        migrations.AddField(
            model_name='design',
            name='svg_right',
            field=models.FileField(blank=True, null=True, upload_to='design_svgs/'),
        ),
    ]
