# Generated by Django 4.2 on 2025-07-21 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize_clothes', '0005_remove_design_svg_data_remove_design_svg_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='design',
            name='svg_back',
        ),
        migrations.RemoveField(
            model_name='design',
            name='svg_front',
        ),
        migrations.RemoveField(
            model_name='design',
            name='svg_left',
        ),
        migrations.RemoveField(
            model_name='design',
            name='svg_right',
        ),
        migrations.AddField(
            model_name='design',
            name='svg_file',
            field=models.FileField(blank=True, null=True, upload_to='design_svgs/'),
        ),
    ]
