# Generated by Django 4.2 on 2025-07-21 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customize_clothes', '0006_remove_design_svg_back_remove_design_svg_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='svg_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
