# Generated by Django 4.2 on 2025-07-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('submitquotation', '0002_quotation_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='order',
        ),
    ]
