# Generated by Django 4.2 on 2025-07-23 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submitquotation', '0003_remove_quotation_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
