# Generated by Django 4.2 on 2025-07-23 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('submit_order', '0004_order_customer'),
        ('submitquotation', '0004_alter_quotation_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='submit_order.order'),
        ),
    ]
